
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
        - node-exporter:9100

  - job_name: 'postgres-exporter'
    metrics_path: /metrics
    params:
      module: [postgres]
    static_configs:
      - targets:
        - postgres14-primary:5432
        - postgres14-replica1:5432
        - postgres14-replica2:5432
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187
